### ISSUE TITLE
Create new WIKI website and RDF backend

### ISSUE THREAD

**Issue by hvarg** [KnowledgeCaptureAndDiscovery/ODS_wiki_generic#4]
We need a new wiki instance with the RDF backend.

Some students will be uploading data about HIV, so I think the link should be something like:
https://www.organicdatacuration.org/HIV
or 
https://www.organicdatacuration.org/enigma_HIV

**Comment by mosoriob** [comment]
Wiki
https://www.organicdatacuration.org/HIV/index.php/Main_Page

Endpoint:
https://endpoint.linkedearth.isi.edu/#/dataset/hiv/query
